import type { ReportLanguage } from '../types/analysis';

export const normalizeReportLanguage = (value?: string | null): ReportLanguage => {
  if (value === 'en') return 'en';
  if (value === 'ko') return 'ko';
  return 'ko';
};

const reportTextKo = {
  keyInsights: '핵심 인사이트',
  noAnalysisSummary: '분석 요약이 아직 없습니다',
  actionAdvice: '투자 의견',
  noAdvice: '의견 없음',
  trendPrediction: '추세 전망',
  noPrediction: '전망 없음',
  marketSentiment: '시장 심리',
  strategyPoints: '전략 포인트',
  sniperLevels: '매매 기준가',
  idealBuy: '이상적 진입',
  secondaryBuy: '보조 진입',
  stopLoss: '손절',
  takeProfit: '익절',
  noValue: '--',
  newsFeed: '뉴스 피드',
  relatedNews: '관련 뉴스',
  refresh: '새로고침',
  retry: '다시 시도',
  dismiss: '닫기',
  details: '자세히 보기',
  loadingNews: '뉴스를 불러오는 중...',
  noNews: '관련 뉴스 없음',
  noNewsDescription: '잠시 후 새로고침해 최신 업데이트를 확인하세요.',
  openLink: '열기',
  transparency: '투명성',
  traceability: '데이터 추적성',
  rawResult: '원본 분석 결과',
  analysisSnapshot: '분석 스냅샷',
  copy: '복사',
  copied: '복사됨',
  recordId: '기록 ID',
  fullReport: '전체 분석 리포트',
  loadingReport: '리포트를 불러오는 중...',
  loadReportFailed: '리포트 로드 실패',
  copyMarkdownSource: 'Markdown 원문 복사',
  copyPlainText: '일반 텍스트 복사',
  analysisModel: '모델',
  fearGreedIndex: '공포 탐욕 지수',
  boardLinkage: '섹터 연계',
  relatedBoards: '관련 섹터',
  leadingBoard: '선도',
  laggingBoard: '후행',
  neutralBoard: '중립',
  reanalyze: '재분석',
};

const reportTextEn: typeof reportTextKo = {
  keyInsights: 'KEY INSIGHTS',
  noAnalysisSummary: 'No analysis summary yet',
  actionAdvice: 'Action Advice',
  noAdvice: 'No advice yet',
  trendPrediction: 'Trend Outlook',
  noPrediction: 'No forecast yet',
  marketSentiment: 'Market Sentiment',
  strategyPoints: 'STRATEGY POINTS',
  sniperLevels: 'Action Levels',
  idealBuy: 'Ideal Entry',
  secondaryBuy: 'Secondary Entry',
  stopLoss: 'Stop Loss',
  takeProfit: 'Take Profit',
  noValue: '--',
  newsFeed: 'NEWS FEED',
  relatedNews: 'Related News',
  refresh: 'Refresh',
  retry: 'Retry',
  dismiss: 'Close',
  details: 'View details',
  loadingNews: 'Loading news...',
  noNews: 'No related news',
  noNewsDescription: 'Refresh later to check for the latest updates.',
  openLink: 'Open',
  transparency: 'TRANSPARENCY',
  traceability: 'Data Traceability',
  rawResult: 'Raw Analysis Result',
  analysisSnapshot: 'Analysis Snapshot',
  copy: 'Copy',
  copied: 'Copied!',
  recordId: 'Record ID',
  fullReport: 'Full Analysis Report',
  loadingReport: 'Loading report...',
  loadReportFailed: 'Failed to load report',
  copyMarkdownSource: 'Copy Markdown Source',
  copyPlainText: 'Copy Plain Text',
  analysisModel: 'Model',
  fearGreedIndex: 'Fear & Greed Index',
  boardLinkage: 'BOARD LINKAGE',
  relatedBoards: 'Related Boards',
  leadingBoard: 'Leading',
  laggingBoard: 'Lagging',
  neutralBoard: 'Neutral',
  reanalyze: 'Reanalyze',
};

const REPORT_TEXT: Record<ReportLanguage, typeof reportTextKo> = {
  zh: reportTextKo,
  ko: reportTextKo,
  en: reportTextEn,
};

export const getReportText = (language?: string | null) => REPORT_TEXT[normalizeReportLanguage(language)];
